### ISSUE TITLE
支持composer

### ISSUE THREAD

**Issue by 18y** [biangbiang/wxpay-php#2]
支持composer更好。。。。。

**Comment by biangbiang** [comment]
这个项目只是当年我完成工作后，简单整理的一个笔记而已。

我并没有把它做成一个可以直接用的组件的想法，后续也一直没有跟着微信支付文档的更新而更新。

此外，这几年我也没有接触微信相关的开发工作！

---

如果你有这个需求，我可以尽力帮助你！

**Comment by 18y** [comment]
使用了一下你的这个sdk, 确实比官方的 wiki 更加简单易懂
希望能够更加完善...

**Comment by biangbiang** [comment]
这个还没失效么？毕竟已经两年没更新了！
那我近期安排时间重新更新下！

**Comment by biangbiang** [comment]
@18y 
很抱歉，我重新看了下这个项目，这个项目其实并不是一个SDK，它只是我当时跑通微信支付的一个总结而已，更多可以认为是一个心路历程。
如果你需要一个完善且不过时的SDK，甚至让它支持composer，这是一个长期维护的工作，最好是让微信支付官方来完成这个工作。
